model_type: gpt-4.1-2025-04-14

num_process: 4
temperature: 0.0  # Temperature for sampling.

datasets:
  - dataset_path: "/workspace/language_model/data/all_data.json"
    dataset_name: "multimodal_rewardbench"
    dataset_split: test
    load_local_image: True
    image_folder: "/workspace/multimodal_rewardbench/data/"
    swap: False
  # - dataset_path: "MMInstruction/VL-RewardBench"
  #   dataset_name: "vl_rewardbench"
  #   dataset_split: test
  #   load_local_image: False
  #   image_folder: "/workspace/language_model/inference/tmp/vl_rewardbench/"
  #   swap: False

num_prompts: 4
modality: image

time_generate: True

data_chunk_size: 100
start_idx: 0

output_dir: results/
